version: '3'

services:
    acl-dashboard:
        image: irpinesctec/acl-dashboard:latest
        environment:
            - VUE_APP_KEYCLOAK_REALM=master
            - VUE_APP_KEYCLOAK_CLIENT_ID=acl-dashboard
            - VUE_APP_MIDDLEWARE_URL=http://localhost:8080/
            - VUE_APP_MAPPINGS_BASE_PATH=resource/
            - VUE_APP_AUTHZ_BASE_PATH=authz/
        restart: always