name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  release:
    name: Release artifact to GitHub releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: npm-build
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-${{ github.run_number }}.zip
          asset_content_type: application/zip
      
  build:
    name: Build Vue.js project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-build
          path: dist/
