# Workflow for building the acl-dashboard
# - Publishes a source-code release on GitHub
# - Builds and publishes a Docker image on DockerHub

name: CI to Docker Hub

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ]
    tags:
      - '**'

jobs:
  build-npm:
    name: Build Vue.js project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-build
          path: dist/

  release:
    name: Release artifact to GitHub releases
    runs-on: ubuntu-latest
    needs: build-npm
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: npm-build

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-${{ github.run_number }}.zip
          asset_content_type: application/zip

  release-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # Set on project's Action Secrets
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Builds
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: irpinesctec/acl-dashboard:${{ env.RELEASE_VERSION }},irpinesctec/acl-dashboard:latest
          build-args: |
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
